# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: MortisCMS 0.1.20 ruby lib

Gem::Specification.new do |s|
  s.name = "MortisCMS"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors       = ["Brendan Ragan"]
  s.email         = ["lordmortis@gmail.com"]
  s.date          = "2015-02-13"
  s.summary       = "A simple, stupid CMS for Rails 4"
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = `git ls-files -z`.split("\x0")
  s.rubygems_version = "2.2.2"
  s.license       = "MIT"


  s.add_dependency 'RedCloth', '>= 4.2'
  s.add_dependency 'haml-rails', '>= 0.5.3'
  s.add_dependency 'paperclip', '~> 4.1'
  s.add_dependency 'paperclip-meta', '>= 0'
  s.add_development_dependency "bundler", "~> 1.7"
  s.add_development_dependency "rake", "~> 10.0"
end

